-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.cities
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1000 CACHE 1 ),
    city_name character varying(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    user_id integer NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    identity_no character varying(11) NOT NULL,
    birth_year integer NOT NULL,
    position_id integer NOT NULL,
    id integer NOT NULL,
    email character varying(60) NOT NULL,
    password character varying(60) NOT NULL,
    verified boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(60) NOT NULL,
    website character varying(30) NOT NULL,
    phone character varying(10) NOT NULL,
    verified_by_system boolean NOT NULL,
    id integer NOT NULL,
    email character varying(60) NOT NULL,
    password character varying(60) NOT NULL,
    verified boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_advertisements
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100000 CACHE 1 ),
    description character varying(500) NOT NULL,
    city_id integer NOT NULL,
    position_id integer NOT NULL,
    employer_id integer NOT NULL,
    release_date date NOT NULL,
    deadline date NOT NULL,
    min_salary integer,
    max_salary integer,
    open_positions_amount integer NOT NULL,
    active boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.personnels
(
    user_id integer NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    id integer NOT NULL,
    email character varying(60) NOT NULL,
    password character varying(60) NOT NULL,
    verified boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.positions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100000 CACHE 1 ),
    position_name character varying(60) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100000 CACHE 1 ),
    email character varying(60) NOT NULL,
    password character varying(60) NOT NULL,
    verified boolean NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.employees
    ADD FOREIGN KEY (position_id)
    REFERENCES public.positions (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (position_id)
    REFERENCES public.positions (id)
    NOT VALID;


ALTER TABLE public.personnels
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;